### ISSUE TITLE
Getting signature mismatch when requesting my user after getting access token

### ISSUE THREAD

**Issue by jasonmerino** [WP-API/OAuth1#203] opened 2017-02-18 14:27 UTC
I'm not sure if this is an issue for this repo or for the main WP-API repo, but I've got a problem where I have gone through all the authentication steps [here](https://oauth1.wp-api.org/docs/basics/Auth-Flow.html) and have received an access token and token secret but when I go to request my user from `http://mysite.com/wp-json/wp/v2/users/me` I keep getting a 401 with `json_oauth1_signature_mismatch` in the JSON response.

I'm not completely sure that I'm sending the request to get my user correctly, but I haven't been able to find a good guide yet on how requests should be formatted after getting the access token in OAuth 1 (aside from [this oauth.net spec](https://oauth.net/core/1.0a/#anchor12)).

My app is in React Native so all my requests are done with the [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) as I was having a difficult time finding a good OAuth 1 client which would support Wordpress REST API OAuth.

If I could just get help in how that request to get my user is supposed to be formatted, even a CURL command that I could translate to Fetch, that would be so helpful.

Thanks!

**Comment by joehoyle** [comment] 2017-05-18 04:58
Closing as dupe of #200

**Closed by joehoyle** 2017-05-18 04:58 UTC
